# Generated by Django 4.1.3 on 2022-11-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('images', models.ImageField(upload_to='photos')),
                ('description', models.TextField()),
            ],
        ),
    ]
